version: '3'
services:
  mysql:
    image: mysql:5.7.26
    # network_mode: "host" # 如果需要容器使用宿主机IP(内网IP)，则可以配置此项
    container_name: abp-pro-mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
    restart: always # 设置容器自启模式
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置utf8字符集
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - MYSQL_ROOT_PASSWORD=1q2w3E* # 设置root密码
    volumes:
       - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
    ports:
        - "3307:3306"
    networks:
      - lionAbpPro 
      
  redis:
    image: redis:5.0.4
    container_name: abp-pro-redis
    restart: always
    command: redis-server  # 启动redis命令
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
    ports:
        - "6380:6379"
    networks:
      - lionAbpPro  

  rabbitMq:
    image: rabbitmq:management
    container_name: abp-pro-rabbitMq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1q2w3E*
    networks:
      - lionAbpPro      

  consul:
    image: consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -node=consul_Server1 -bootstrap-expect=1 -ui
    networks:
      - lionAbpPro

networks:
  lionAbpPro:
    driver: bridge      