name: Vben2.7
on:
  push:
    tags:
      - "*"
jobs:
  Push-DockerHub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Set Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Build And Push Docker Hub
        run: cd vben271 &&
          npm install &&
          npm run build &&
          docker login -u zzzwangjun -p ${{secrets.dockerHubPassword}} &&
          docker build -t abp-vnext-pro-ui:${{ steps.vars.outputs.tag }} . &&
          docker tag  abp-vnext-pro-ui:${{ steps.vars.outputs.tag }} zzzwangjun/abp-vnext-pro-ui:${{ steps.vars.outputs.tag }} &&
          docker push zzzwangjun/abp-vnext-pro-ui:${{ steps.vars.outputs.tag }}
